version: "3.9"

services:
  # web:
  # TO COMPLETE
  app:
    image: myapp
  
  #database:
  #  image: postgres:14
  #  environment:
  #    - POSTGRES_PASSWORD=dev_password
  #    - POSTGRES_USER=si5_sacc
  #    - POSTGRES_DB=td_1